import { defineTable } from '../types';

export const leadsTable = defineTable({
  model: 'Lead',
  table: 'leads',
  description: 'Sales leads scoped to an organization',
  tenantScoped: true,
  columns: [
    { name: 'id', dbColumn: 'id', type: 'UUID', primaryKey: true },
    { name: 'organizationId', dbColumn: 'organization_id', type: 'UUID', indexed: true, tenantKey: true, foreignKey: { table: 'organizations', column: 'id' } },
    { name: 'firstName', dbColumn: 'first_name', type: 'STRING' },
    { name: 'lastName', dbColumn: 'last_name', type: 'STRING' },
    { name: 'email', dbColumn: 'email', type: 'STRING', nullable: true, indexed: true },
    { name: 'phone', dbColumn: 'phone', type: 'STRING', indexed: true },
    { name: 'alternatePhone', dbColumn: 'alternate_phone', type: 'STRING', nullable: true },
    { name: 'status', dbColumn: 'status', type: 'ENUM', enumValues: ['NEW', 'CONTACTED', 'QUALIFIED', 'NEGOTIATION', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_DONE', 'BOOKED', 'LOST', 'WON'], default: 'NEW', indexed: true },
    { name: 'priority', dbColumn: 'priority', type: 'ENUM', enumValues: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], default: 'MEDIUM' },
    { name: 'budget', dbColumn: 'budget', type: 'DECIMAL', nullable: true },
    { name: 'requirements', dbColumn: 'requirements', type: 'TEXT', nullable: true },
    { name: 'address', dbColumn: 'address', type: 'TEXT', nullable: true },
    { name: 'city', dbColumn: 'city', type: 'STRING', nullable: true },
    { name: 'state', dbColumn: 'state', type: 'STRING', nullable: true },
    { name: 'pincode', dbColumn: 'pincode', type: 'STRING', nullable: true },
    { name: 'sourceId', dbColumn: 'source_id', type: 'UUID', indexed: true, foreignKey: { table: 'lead_sources', column: 'id' } },
    { name: 'assignedToId', dbColumn: 'assigned_to_id', type: 'UUID', nullable: true, indexed: true, foreignKey: { table: 'users', column: 'id' } },
    { name: 'createdById', dbColumn: 'created_by_id', type: 'UUID', foreignKey: { table: 'users', column: 'id' } },
    { name: 'propertyId', dbColumn: 'property_id', type: 'UUID', nullable: true, foreignKey: { table: 'properties', column: 'id' } },
    { name: 'projectId', dbColumn: 'project_id', type: 'UUID', nullable: true, foreignKey: { table: 'projects', column: 'id' } },
    { name: 'createdAt', dbColumn: 'created_at', type: 'DATETIME' },
    { name: 'updatedAt', dbColumn: 'updated_at', type: 'DATETIME' },
    { name: 'deletedAt', dbColumn: 'deleted_at', type: 'DATETIME', nullable: true },
  ],
  indexes: ['organizationId', 'status', 'assignedToId', 'sourceId', 'phone', 'email'],
  relations: ['Organization', 'LeadSource', 'User', 'Property', 'Project', 'LeadNote', 'LeadTimeline', 'SiteVisit', 'Booking'],
});
