import { defineTable } from '../types';

export const propertiesTable = defineTable({
  model: 'Property',
  table: 'properties',
  description: 'Property listings scoped to an organization',
  tenantScoped: true,
  columns: [
    { name: 'id', dbColumn: 'id', type: 'UUID', primaryKey: true },
    { name: 'organizationId', dbColumn: 'organization_id', type: 'UUID', indexed: true, tenantKey: true, foreignKey: { table: 'organizations', column: 'id' } },
    { name: 'title', dbColumn: 'title', type: 'STRING' },
    { name: 'description', dbColumn: 'description', type: 'TEXT', nullable: true },
    { name: 'listingCategory', dbColumn: 'listing_category', type: 'ENUM', enumValues: ['BUY', 'RENT', 'COMMERCIAL', 'NEW_PROJECTS', 'PG', 'PLOT', 'LUXURY'], default: 'BUY', indexed: true },
    { name: 'type', dbColumn: 'type', type: 'ENUM', enumValues: ['APARTMENT', 'BUILDER_FLOOR', 'VILLA', 'PLOT', 'COMMERCIAL', 'OFFICE', 'SHOP', 'WAREHOUSE', 'COWORKING_SPACE'], indexed: true },
    { name: 'status', dbColumn: 'status', type: 'ENUM', enumValues: ['AVAILABLE', 'UNDER_OFFER', 'SOLD', 'RENTED', 'OFF_MARKET'], default: 'AVAILABLE', indexed: true },
    { name: 'price', dbColumn: 'price', type: 'DECIMAL' },
    { name: 'area', dbColumn: 'area', type: 'DECIMAL' },
    { name: 'carpetArea', dbColumn: 'carpet_area', type: 'DECIMAL', nullable: true },
    { name: 'builtUpArea', dbColumn: 'built_up_area', type: 'DECIMAL', nullable: true },
    { name: 'superArea', dbColumn: 'super_area', type: 'DECIMAL', nullable: true },
    { name: 'bedrooms', dbColumn: 'bedrooms', type: 'INTEGER', nullable: true },
    { name: 'bathrooms', dbColumn: 'bathrooms', type: 'INTEGER', nullable: true },
    { name: 'address', dbColumn: 'address', type: 'STRING' },
    { name: 'city', dbColumn: 'city', type: 'STRING', indexed: true },
    { name: 'state', dbColumn: 'state', type: 'STRING' },
    { name: 'pincode', dbColumn: 'pincode', type: 'STRING', nullable: true },
    { name: 'locality', dbColumn: 'locality', type: 'STRING', default: "''", indexed: true },
    { name: 'sector', dbColumn: 'sector', type: 'STRING', nullable: true },
    { name: 'landmark', dbColumn: 'landmark', type: 'STRING', nullable: true },
    { name: 'latitude', dbColumn: 'latitude', type: 'DECIMAL', nullable: true },
    { name: 'longitude', dbColumn: 'longitude', type: 'DECIMAL', nullable: true },
    { name: 'builderName', dbColumn: 'builder_name', type: 'STRING', nullable: true },
    { name: 'propertyAge', dbColumn: 'property_age', type: 'ENUM', enumValues: ['UNDER_CONSTRUCTION', 'READY_TO_MOVE', 'NEW', 'ONE_TO_FIVE_YEARS', 'FIVE_TO_TEN_YEARS', 'TEN_PLUS_YEARS'], nullable: true },
    { name: 'furnishing', dbColumn: 'furnishing', type: 'ENUM', enumValues: ['FULLY_FURNISHED', 'SEMI_FURNISHED', 'UNFURNISHED'], nullable: true },
    { name: 'facing', dbColumn: 'facing', type: 'ENUM', enumValues: ['NORTH', 'SOUTH', 'EAST', 'WEST'], nullable: true },
    { name: 'possessionStatus', dbColumn: 'possession_status', type: 'ENUM', enumValues: ['IMMEDIATE', 'WITHIN_3_MONTHS', 'WITHIN_6_MONTHS', 'WITHIN_1_YEAR'], nullable: true },
    { name: 'possessionDate', dbColumn: 'possession_date', type: 'STRING', nullable: true, description: 'ISO date or quarter label e.g. Q1 2027' },
    { name: 'roiPotential', dbColumn: 'roi_potential', type: 'DECIMAL', nullable: true },
    { name: 'isVerified', dbColumn: 'is_verified', type: 'BOOLEAN', default: 'true' },
    { name: 'hasRera', dbColumn: 'has_rera', type: 'BOOLEAN', default: 'false' },
    { name: 'reraId', dbColumn: 'rera_id', type: 'STRING', nullable: true },
    { name: 'videoTourUrl', dbColumn: 'video_tour_url', type: 'STRING', nullable: true },
    { name: 'virtualTourUrl', dbColumn: 'virtual_tour_url', type: 'STRING', nullable: true },
    { name: 'amenities', dbColumn: 'amenities', type: 'ARRAY' },
    { name: 'brochureUrl', dbColumn: 'brochure_url', type: 'STRING', nullable: true },
    { name: 'isActive', dbColumn: 'is_active', type: 'BOOLEAN', default: 'true' },
    { name: 'projectId', dbColumn: 'project_id', type: 'UUID', nullable: true, foreignKey: { table: 'projects', column: 'id' } },
    { name: 'createdAt', dbColumn: 'created_at', type: 'DATETIME' },
    { name: 'updatedAt', dbColumn: 'updated_at', type: 'DATETIME' },
    { name: 'deletedAt', dbColumn: 'deleted_at', type: 'DATETIME', nullable: true },
  ],
  indexes: ['organizationId', 'status', 'city', 'type', 'listingCategory', 'locality'],
  relations: ['Organization', 'Project', 'PropertyImage', 'Lead', 'Booking'],
});
